export const usersData = [
  {
    id: 1,
    name: "Rahul",
    age: 28,
    city: "Bangalore",
    salary: 85000,
    role: "Frontend Developer",
    experience: 4,
    skills: ["React", "JavaScript", "CSS"],
    isActive: true,
  },
  {
    id: 2,
    name: "Priya",
    age: 25,
    city: "Mumbai",
    salary: 65000,
    role: "Backend Developer",
    experience: 2,
    skills: ["Node.js", "MongoDB", "Express"],
    isActive: true,
  },
  {
    id: 3,
    name: "Amit",
    age: 32,
    city: "Delhi",
    salary: 120000,
    role: "Full Stack Developer",
    experience: 7,
    skills: ["React", "Node.js", "PostgreSQL"],
    isActive: false,
  },
  {
    id: 4,
    name: "Sneha",
    age: 29,
    city: "Bangalore",
    salary: 95000,
    role: "Frontend Developer",
    experience: 5,
    skills: ["React", "TypeScript", "Next.js"],
    isActive: true,
  },
  {
    id: 5,
    name: "Vikram",
    age: 24,
    city: "Pune",
    salary: 55000,
    role: "Junior Developer",
    experience: 1,
    skills: ["JavaScript", "HTML", "CSS"],
    isActive: true,
  },
  {
    id: 6,
    name: "Anjali",
    age: 35,
    city: "Hyderabad",
    salary: 140000,
    role: "Tech Lead",
    experience: 10,
    skills: ["React", "Node.js", "AWS", "Docker"],
    isActive: false,
  },
  {
    id: 7,
    name: "Rohan",
    age: 27,
    city: "Bangalore",
    salary: 78000,
    role: "Frontend Developer",
    experience: 3,
    skills: ["React", "JavaScript", "Redux"],
    isActive: true,
  },
  {
    id: 8,
    name: "Neha",
    age: 31,
    city: "Chennai",
    salary: 110000,
    role: "Full Stack Developer",
    experience: 6,
    skills: ["React", "Node.js", "TypeScript"],
    isActive: true,
  },
];
